### ISSUE TITLE
[BUG] No Video Embed in Discord.

### ISSUE THREAD

**Issue by frk1337** [spikehidden/YBPVE#1]
how do i use this code, whatever i did it gave http 500 error

**Comment by spikehidden** [comment]
I need a little more info then just it throws an error.

**Please answer the following questions:**
- What other plugins do you use?
- Did you put the plugin in the right directory?
- Which version of YOURLS are you using?
- Which version of PHP are you using?
- What Webserver do you use? (Apache, Nginx, ect.)

**Comment by frk1337** [comment]
Code Working (I did not activate yourls/manage plugin) but Now embed just seen photo 
Examp 
![Screenshot_20230301-225502_Discord](https://user-images.githubusercontent.com/116391392/222251706-d0f7f0ec-0bd0-4216-8dd3-e4e83299b93c.png)

**Comment by spikehidden** [comment]
Weird, can you send me the short link you have generated and also the long URL you have shortened?\
Do you have any other plugins installed that manage redirects? (Like replacing the status code 301 with 302, ect.)\
Have you taken the URL you want to shorten from the actual source instance or from another one?

**Comment by frk1337** [comment]
No,plugin not installed(just your plugin installed)
Tryed your video ,Should I shorten it to https? Or not [Link](https://cliptube.org/w/6203b357-bb41-431b-b698-2170d83f996b)

**Comment by spikehidden** [comment]
> I need a little more info then just it throws an error.
> 
> **Please answer the following questions:**
> 
> * Which version of YOURLS are you using?
> * Which version of PHP are you using?
> * What Webserver do you use? (Apache, Nginx, ect.)

It would be great if you could answer my questions above as those might solve the problem.\
But most important question of them all is probably:

* Do you have the curl extension for PHP installed?

Because if not the plugin will not be able to work at all, as it makes API calls via curl to get the video source, ect.

And also could you provide me the URL of the link you generated with your version of YOURLS.

**Comment by frk1337** [comment]
Yourls 1.9.1, CPANEL shared hosting,php7.4(i can change) extension Let me check, if it's not active, I'll let you know if it doesn't work after activating it.

**Comment by frk1337** [comment]
So i activated curl and worked

**Comment by spikehidden** [comment]
I'm glad everything works now.
